src/Maxim/CMSBundle/Entity/User.php
<?php
/**
 * Author: Maxim
 * Date: 28/01/14
 * Time: 15:19
 * Property of MCSuite
 */

namespace Maxim\CMSBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Maxim\CMSBundle\Model\User as BaseUser;
use Maxim\CMSBundle\Model\UserInterface;

class User extends BaseUser
{

    protected $id;

    protected $mcUsername;

    protected $mcPassword;

    protected $mcUuid;

    protected $awards;

    public function getGroup()
    {
        if($this->groups[0] != null)
            return $this->groups[0];

        $group = new Group('Member', array('ROLE_MEMBER'));
        $group->setCssClass('group-member');
        return $group;

    }

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Hook on pre-persist operations
     */
    public function prePersist()
    {
        $this->createdAt = new \DateTime;
        $this->updatedAt = new \DateTime;
    }

    /**
     * Hook on pre-update operations
     */
    public function preUpdate()
    {
        $this->updatedAt = new \DateTime;
    }

    public function isGranted($role)
    {
        foreach($this->getGroups() as $g)
        {
            foreach($g->getRoles() as $role)
            {
                if(strtoupper($role) == strtoupper($role))
                    return true;
            }
        }
    }

    public function isBanned()
    {
        return $this->isGranted(Group::ROLE_BANNED);
    }

    /**
     * Returns the gender list
     *
     * @return array
     */
    public static function getGenderList()
    {
        return parent::getGenderList();
    }

    /**
     * @param mixed $mcUsername
     */
    public function setMcUsername($mcUsername)
    {
        $this->mcUsername = $mcUsername;
    }

    /**
     * @return mixed
     */
    public function getMcUsername()
    {
        return $this->mcUsername;
    }

    /**
     * @param mixed $mcPassword
     */
    public function setMcPassword($mcPassword)
    {
        $this->mcPassword = $mcPassword;
    }

    /**
     * @return mixed
     */
    public function getMcPassword()
    {
        return $this->mcPassword;
    }

    /**
     * @return mixed
     */
    public function getMcUuid()
    {
        return $this->mcUuid;
    }

    /**
     * @param mixed $mcUuid
     */
    public function setMcUuid($mcUuid)
    {
        $this->mcUuid = $mcUuid;
    }

    /**
     * @return mixed
     */
    public function getAwards()
    {
        return $this->awards;
    }

    /**
     * @param mixed $awards
     */
    public function setAwards($awards)
    {
        $this->awards = $awards;
    }

    public function addAward($award)
    {
        $this->awards[] = $award;
    }
} 

src/Maxim/CMSBundle/Resources/views/admin.DIS/user/profile.html.twig
{% extends 'MaximCMSBundle:admin:index.html.twig' %}

{% block middle %}
<div id="middle_menu_top">
	<div class="vertical">
		<h1>User</h1>
	</div>
</div>
<div id="middle_menu_small">
	<ul>
		<li>
			<a href="#">User</a>
		</li>
		<li>
			<a href="#">{{ user.username }}</a>
		</li>
	</ul>
</div>
<div id="middle_content">
	<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
    </script>
</head>
	<div class="window">
		<div class="window-header">
			<h6>User: {{ user.username }}</h6>
		</div>
		<div class="window-content">
			<!-- USER PROFILE -->
			{% if user.banned %}
			<button id="user-unban">unban User</button>
			{% else %}
			<button id="user-ban">Ban User</button>
			{% endif %}
			<div id="tabs">
			    <ul>
			        <li><a href="#tabs-1">Profile</a></li>
			        <li><a href="#tabs-2">Accounts</a></li>
			    </ul>
			    <div id="tabs-1">
			    	<form action="{{ path('admin_user_update_ajax') }}" id="frmEditUser" method="post">
						<p>
							<label for="name">Username</label>
							<br/>
							<input type="text" name="_admin_user_username" class="inputbox" value="{{ user.username }}" id="username" >
						</p>
						<p>
							<label for="name">Email</label>
							<br/>
							<input type="text" name="_admin_user_email" class="inputbox" value="{{ user.email }}" id="email" >
						</p>
						<p>
							<label for="name">LastIp</label>
							<br/>
							<input type="text" name="_admin_user_lastIp" class="inputbox" value="{{ user.lastIp }}" id="lastIp" >
						</p>
						<p>
							<label for="name">LastLogin</label>
							<br/>
							<input type="text" name="_admin_user_lastLogin" class="inputbox" value="{{ user.lastLogin|date('Y-m-d h:i:s') }}" id="lastLogin" >
						</p>
						<p>
							<label for="name">dateOfBirth</label>
							<br/>
							<input type="text" name="_admin_user_dateOfBirth" class="inputbox" value="{{ user.dateOfBirth|date('Y-m-d') }}" id="dateOfBirth" >
						</p>
						<p>
							<label for="name">Location</label>
							<br/>
							<input type="text" name="_admin_user_location" class="inputbox" value="{{ user.location }}" id="location" >
						</p>
						<p>
							<label for="name">Skype</label>
							<br/>
							<input type="text" name="_admin_user_skype" class="inputbox" value="{{ user.skype }}" id="skype" />
						</p>
						<p>
							<select id="groups" class="multiselect" multiple="multiple" name="groups[]">
								{% for group in groups %}
                                    <option value="{{ group.id }}">{{ group.name }}</option>
                                {% endfor %}
                                {% for user_groups in user.userGroups %}
                                    <option value="{{ user_groups.id }}" selected="selected">{{ user_groups.name }}</option>
                                {% endfor %}
							</select>
						</p>
						<input type="hidden" name="_admin_user_id" value="{{ user.id }}" id="admin_user_id_hdn"/>
						<button type="submit" id="btnSaveUser">Save user</button>
						
						<div id="msgbox"></div>
					</form>
			    </div>
			    <div id="tabs-2">
			    	{% for account in accounts %}
						<img src="https://minotar.net/avatar/{{ account.accountname }}/50.png" alt="{{ account.accountname }}" />
						{{ account.accountname }}
					{% else %}
					<p>
						No accounts have been found.
					</p>
					{% endfor %}
			    </div>
			</div>
		</div>
		<!-- BAN POPUP -->
		<div id="ban-user">
			<form action="{{ path('admin_ban_user') }}" id="frmBanUser" method="post">
				<fieldset>
					<label for="ban_permanent" >Permanent?</label>
					<input type="checkbox" name="_ban_permanent" id="ban_permanent" />
					<br/>
					<input type="text" name="_ban_reason" id="ban_reason" placeholder="ban reason:" /><br/>
					<input type="text" name="_ban_time" id="ban_time" placeholder="ban time: "/>
				</fieldset>
			</form>
			<script>
				$(document).ready(function() {
					$('#ban_permanent').change(function(){
						if(!$('#ban_permanent').is(':checked'))
						{
							$('#ban_time').slideDown(300);
						}
						else
						{
							$('#ban_time').slideUp(300);
						}
					});
				});
			</script>
		</div>
	</div>
</div>

<script>
$(document).ready(function() {
	$("#groups").multiselect();
	
	$("#frmEditUser").submit(function() {
		AJAX.post(
			$("#frmEditUser").attr("action"), 
			{
				_admin_user_id 			: $('#admin_user_id_hdn').val(),
				_admin_user_username 	: $("#frmEditUser #username").val(),
				_admin_user_email 		: $("#frmEditUser #email").val(),
				_admin_user_lastIp 		: $("#frmEditUser #lastIp").val(),
				_admin_user_lastLogin 	: $("#frmEditUser #lastLogin").val(),
				_admin_user_dateOfBirth : $("#frmEditUser #dateOfBirth").val(),
				_admin_user_location 	: $("#frmEditUser #location").val(),
				_admin_user_skype 		: $("#frmEditUser #skype").val(),
				_admin_user_groups		: $("#frmEditUser #groups").val()
			}, 
			$("#msgbox") ,
			$('#btnSaveUser')
		);
		return false;
	});
	$('#user-unban').button().click(function( event )
	{
		console.log('unban clicked');
		event.preventDefault();
		AJAX.post_noButton(
			"{{ path('admin_unban_user') }}", 
			{
				_ban_user : $('#username').val()
			}, 
			$("#msgbox") 
		);	
	});
			
	
	//BUTTON
	$( "#user-ban" ).button().click(function( event ) {
		event.preventDefault();
		$('#ban-user').dialog("open");
	});
	
});
$(function(id) {
	$( "#ban-user" ).dialog({
		height: 350,
		width: 400,
		modal: true,
		autoOpen: false,
		buttons: {
			"Ban user": function(){
				//get the url for the form
				AJAX.post_noButton(
					$("#frmBanUser").attr("action"), 
					{
						_ban_reason : $("#ban_reason").val(),
						_ban_time : $("#ban_time").val(),
						_ban_permanent : $("#ban_permanent:checked").val(),
						_ban_user : $('#username').val()
					}, 
					$("#msgbox") 
				);							
			},
			Cancel: function(){
				$(this).dialog("close");
			},
			close: function(){
				$(this).dialog("close");
			}
		}
	});
});

</script>
<style>
	/* multiselect styles */
	.multiselect {
		width: 460px;
		height: 200px;
	}
</style>
{% endblock middle %}